[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
evm_version = "prague"
alphanet = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
